namespace DotNet.Debugging.Remote.Protocol;

// The debugger callbacks the agent reports, numbered in the order of ICorDebugManagedCallback and ICorDebugManagedCallback2
public enum RemoteCallback : ushort {
    Breakpoint = 1,
    StepComplete = 2,
    Break = 3,
    Exception = 4,
    EvalComplete = 5,
    EvalException = 6,
    CreateProcess = 7,
    ExitProcess = 8,
    CreateThread = 9,
    ExitThread = 10,
    LoadModule = 11,
    UnloadModule = 12,
    LoadClass = 13,
    UnloadClass = 14,
    DebuggerError = 15,
    LogMessage = 16,
    LogSwitch = 17,
    CreateAppDomain = 18,
    ExitAppDomain = 19,
    LoadAssembly = 20,
    UnloadAssembly = 21,
    ControlCTrap = 22,
    NameChange = 23,
    UpdateModuleSymbols = 24,
    EditAndContinueRemap = 25,
    BreakpointSetError = 26,
    FunctionRemapOpportunity = 27,
    CreateConnection = 28,
    ChangeConnection = 29,
    DestroyConnection = 30,
    Exception2 = 31,
    ExceptionUnwind = 32,
    FunctionRemapComplete = 33,
    MDANotification = 34,
}
