namespace DotNet.Debugging.CorApi;

// https://learn.microsoft.com/dotnet/core/unmanaged-api/metadata/enumerations/corelementtype-enumeration
public enum CorElementType {
    END = 0,
    VOID = 1,
    BOOLEAN = 2,
    CHAR = 3,
    I1 = 4,
    U1 = 5,
    I2 = 6,
    U2 = 7,
    I4 = 8,
    U4 = 9,
    I8 = 10,
    U8 = 11,
    R4 = 12,
    R8 = 13,
    STRING = 14,
    PTR = 15,
    BYREF = 16,
    VALUETYPE = 17,
    CLASS = 18,
    VAR = 19,
    ARRAY = 20,
    GENERICINST = 21,
    TYPEDBYREF = 22,
    I = 24,
    U = 25,
    FNPTR = 27,
    OBJECT = 28,
    SZARRAY = 29,
    MVAR = 30,
    CMOD_REQD = 31,
    CMOD_OPT = 32,
    INTERNAL = 33,
    CMOD_INTERNAL = 34,
    MAX = 35,
    MODIFIER = 64,
    SENTINEL = 65,
    PINNED = 69
}