namespace DotNet.Debugging.CorApi;

public enum CorSerializationType {
    SERIALIZATION_TYPE_UNDEFINED = 0,
    SERIALIZATION_TYPE_BOOLEAN = 0x02,
    SERIALIZATION_TYPE_CHAR = 0x03,
    SERIALIZATION_TYPE_I1 = 0x04,
    SERIALIZATION_TYPE_U1 = 0x05,
    SERIALIZATION_TYPE_I2 = 0x06,
    SERIALIZATION_TYPE_U2 = 0x07,
    SERIALIZATION_TYPE_I4 = 0x08,
    SERIALIZATION_TYPE_U4 = 0x09,
    SERIALIZATION_TYPE_I8 = 0x0a,
    SERIALIZATION_TYPE_U8 = 0x0b,
    SERIALIZATION_TYPE_R4 = 0x0c,
    SERIALIZATION_TYPE_R8 = 0x0d,
    SERIALIZATION_TYPE_STRING = 0x0e,
    SERIALIZATION_TYPE_SZARRAY = 0x1d,
    SERIALIZATION_TYPE_TYPE = 0x50,
    SERIALIZATION_TYPE_TAGGED_OBJECT = 0x51,
    SERIALIZATION_TYPE_FIELD = 0x53,
    SERIALIZATION_TYPE_PROPERTY = 0x54,
    SERIALIZATION_TYPE_ENUM = 0x55
}