namespace DotNet.Debugging.CorApi;

public enum CorSerializationType {
    SERIALIZATION_TYPE_UNDEFINED = 0,
    SERIALIZATION_TYPE_BOOLEAN = 2,
    SERIALIZATION_TYPE_CHAR = 3,
    SERIALIZATION_TYPE_I1 = 4,
    SERIALIZATION_TYPE_U1 = 5,
    SERIALIZATION_TYPE_I2 = 6,
    SERIALIZATION_TYPE_U2 = 7,
    SERIALIZATION_TYPE_I4 = 8,
    SERIALIZATION_TYPE_U4 = 9,
    SERIALIZATION_TYPE_I8 = 10,
    SERIALIZATION_TYPE_U8 = 11,
    SERIALIZATION_TYPE_R4 = 12,
    SERIALIZATION_TYPE_R8 = 13,
    SERIALIZATION_TYPE_STRING = 14,
    SERIALIZATION_TYPE_SZARRAY = 29,
    SERIALIZATION_TYPE_TYPE = 80,
    SERIALIZATION_TYPE_TAGGED_OBJECT = 81,
    SERIALIZATION_TYPE_FIELD = 83,
    SERIALIZATION_TYPE_PROPERTY = 84,
    SERIALIZATION_TYPE_ENUM = 85
}