namespace DotNet.Debugging.CorApi;

// https://learn.microsoft.com/dotnet/core/unmanaged-api/metadata/enumerations/cortypeattr-enumeration
public enum CorTypeAttr {
    tdVisibilityMask = 7,
    tdNotPublic = 0,
    tdPublic = 1,
    tdNestedPublic = 2,
    tdNestedPrivate = 3,
    tdNestedFamily = 4,
    tdNestedAssembly = 5,
    tdNestedFamANDAssem = 6,
    tdNestedFamORAssem = tdVisibilityMask,
    tdLayoutMask = 24,
    tdAutoLayout = tdNotPublic,
    tdSequentialLayout = 8,
    tdExplicitLayout = 16,
    tdExtendedLayout = tdLayoutMask,
    tdClassSemanticsMask = 32,
    tdClass = tdNotPublic,
    tdInterface = tdClassSemanticsMask,
    tdAbstract = 128,
    tdSealed = 256,
    tdSpecialName = 1024,
    tdImport = 4096,
    tdSerializable = 8192,
    tdWindowsRuntime = 16384,
    tdStringFormatMask = 196608,
    tdAnsiClass = tdNotPublic,
    tdUnicodeClass = 65536,
    tdAutoClass = 131072,
    tdCustomFormatClass = tdStringFormatMask,
    tdCustomFormatMask = 12582912,
    tdBeforeFieldInit = 1048576,
    tdForwarder = 2097152,
    tdReservedMask = 264192,
    tdRTSpecialName = 2048,
    tdHasSecurity = 262144
}