<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\Common.Build.props" />

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.DisableRuntimeMarshallingAttribute" />
	</ItemGroup>
</Project>
