<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\Common.Build.props" />
    
    <PropertyGroup>
        <OutputType>Library</OutputType>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <EnableLogging>true</EnableLogging>
    </PropertyGroup>
    <PropertyGroup Condition="'$(EnableLogging)' == 'true'">
        <DefineConstants>$(DefineConstants);LOGGING</DefineConstants>
    </PropertyGroup>

    <ItemGroup Condition="'$(EnableLogging)' == 'true'">
        <PackageReference Include="NLog" />
    </ItemGroup>
</Project>