using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DotNet.Debugging.Remote.Generator;

// The 'Iids' class: the id of every CorApi interface the proxies implement or pass an object as
internal sealed class InterfaceIds {
    private readonly Dictionary<string, CorApiInterface> interfaces = new Dictionary<string, CorApiInterface>();

    public string Reference(CorApiInterface iface) {
        var name = CorApiInterface.IdName(iface.Name);
        interfaces[name] = iface;
        return "Iids." + name;
    }

    public string Write() {
        var text = new StringBuilder();
        text.Append("// <auto-generated/>\n#nullable enable\n\nnamespace DotNet.Debugging.Remote.Proxy;\n\n");
        text.Append("// The interface ids the proxies call through (cordebug.idl, cor.h); the agent queries each handle's object for the one named\n");
        text.Append("internal static class Iids {\n");
        foreach (var pair in interfaces.OrderBy(p => p.Key.StartsWith("MetaData") ? 1 : 0).ThenBy(p => p.Key, System.StringComparer.Ordinal))
            text.Append($"    public static readonly System.Guid {pair.Key} = new System.Guid(\"{pair.Value.Guid}\");\n");
        text.Append("}\n");
        return text.ToString();
    }
}
