using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DotNet.Debugging.Remote.Generator;

// Writes the proxies of the host library: for every [GeneratedComClass] partial class deriving from RemoteObject, the
// constructor and the methods of its CorApi interfaces that are not written by hand, one request to the agent each;
// the 'Iids' table; and the session's map from an interface to the one class implementing it. The interfaces are read
// from the CorApi source files the host project lists as additional files; the kinds a value or a frame comes in
// share their interfaces, so their classes are chosen by the session's own code
[Generator(LanguageNames.CSharp)]
public sealed class ProxyGenerator : IIncrementalGenerator {
    private const string GeneratedComClassAttribute = "System.Runtime.InteropServices.Marshalling.GeneratedComClassAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var classes = context.SyntaxProvider
            .ForAttributeWithMetadataName(GeneratedComClassAttribute,
                static (node, _) => node is ClassDeclarationSyntax,
                static (syntaxContext, _) => (INamedTypeSymbol)syntaxContext.TargetSymbol)
            .Where(static symbol => ProxyClass.IsProxy(symbol))
            .Collect();
        var definitions = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".cs"))
            .Select(static (file, cancellation) => file.GetText(cancellation)?.ToString() ?? string.Empty)
            .Collect();
        var input = classes.Combine(definitions).Combine(context.CompilationProvider);
        context.RegisterSourceOutput(input, static (production, pair) => Emit(production, pair.Left.Left, pair.Left.Right, pair.Right));
    }

    private static void Emit(SourceProductionContext production, ImmutableArray<INamedTypeSymbol> symbols, ImmutableArray<string> definitions, Compilation compilation) {
        var interfaces = CorApiInterface.Parse(definitions);
        var kinds = new TypeKinds(compilation);
        var classes = symbols.Select(s => new ProxyClass(s, interfaces)).OrderBy(c => c.Name, System.StringComparer.Ordinal).ToList();
        var proxied = new HashSet<string>(classes.SelectMany(c => c.Interfaces).Select(i => i.Name));
        var ids = new InterfaceIds();
        foreach (var name in proxied)
            ids.Reference(interfaces[name]);
        foreach (var proxyClass in classes)
            production.AddSource($"{proxyClass.Name}.g.cs", SourceText.From(WriteClass(proxyClass, proxied, interfaces, kinds, ids), Encoding.UTF8));
        production.AddSource("Iids.g.cs", SourceText.From(ids.Write(), Encoding.UTF8));
        production.AddSource("RemoteSession.g.cs", SourceText.From(WriteSession(classes), Encoding.UTF8));
    }

    private static string WriteClass(ProxyClass proxyClass, HashSet<string> proxied, Dictionary<string, CorApiInterface> interfaces, TypeKinds kinds, InterfaceIds ids) {
        var text = new StringBuilder();
        text.Append("// <auto-generated/>\n#nullable enable\nusing System.Runtime.CompilerServices;\nusing DotNet.Debugging.CorApi;\nusing DotNet.Debugging.Remote.Protocol;\n\n");
        text.Append("namespace DotNet.Debugging.Remote.Proxy;\n\n");
        var methods = proxyClass.Interfaces.SelectMany(i => i.Methods).ToList();
        var unsafeClass = methods.Any(m => m.Parameters.Any(p => p.IsPointer));
        text.Append($"{(unsafeClass ? "unsafe " : string.Empty)}partial class {proxyClass.Name} {{\n");
        if (!proxyClass.HasConstructor)
            text.Append($"    public {proxyClass.Name}(RemoteSession session, uint handle) : base(session, handle) {{ }}\n\n");
        // The same name and parameters declared by two interfaces of the class are implemented for each explicitly
        var declarations = methods.GroupBy(m => m.Key()).ToDictionary(g => g.Key, g => g.Count());
        foreach (var iface in proxyClass.Interfaces) {
            var pending = iface.Methods.Where(m => !proxyClass.Implements(iface, m)).ToList();
            if (pending.Count == 0)
                continue;
            text.Append($"    // {iface.Name}\n");
            foreach (var method in pending)
                new ProxyMethod(iface, method, declarations[method.Key()] > 1, proxied, interfaces, kinds, ids).Write(text);
        }
        text.Append("}\n");
        return text.ToString();
    }
    private static string WriteSession(List<ProxyClass> classes) {
        var text = new StringBuilder();
        text.Append("// <auto-generated/>\n#nullable enable\nusing DotNet.Debugging.CorApi;\n\nnamespace DotNet.Debugging.Remote.Proxy;\n\n");
        text.Append("partial class RemoteSession {\n");
        text.Append("    // The proxy of an interface exactly one class implements; null for the interfaces the kinds of values and frames share\n");
        text.Append("    private RemoteObject? CreateUniqueProxy<T>(uint handle) {\n");
        text.Append("        var type = typeof(T);\n");
        var implementations = new Dictionary<string, List<ProxyClass>>();
        foreach (var proxyClass in classes) {
            foreach (var iface in proxyClass.Interfaces) {
                if (!implementations.TryGetValue(iface.Name, out var list))
                    implementations[iface.Name] = list = new List<ProxyClass>();
                list.Add(proxyClass);
            }
        }
        foreach (var pair in implementations.Where(p => p.Value.Count == 1).OrderBy(p => p.Key, System.StringComparer.Ordinal)) {
            text.Append($"        if (type == typeof({pair.Key}))\n");
            text.Append($"            return new {pair.Value[0].Name}(this, handle);\n");
        }
        text.Append("        return null;\n    }\n}\n");
        return text.ToString();
    }
}
